name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: bazel-contrib/setup-bazel@8cb04a772ab4c1eb984e9c1b493a182e96c5e425 # 0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          cache-save: ${{ github.event_name != 'pull_request' }}
      - name: Run tests and static analysis
        run: bazel test //...
      - name: Generate coverage report
        run: bazel coverage //:all_tests --combined_report=lcov
      - name: Build multi-platform container archive
        run: bazel build //:container_tarball
